routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth']], function () {
    Route::resource('companies', 'CompanyController');
    Route::resource('employees', 'EmployeeController');
});

Auth::routes(['register' => false]);
Route::get('/home', 'HomeController@index')->name('home');

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model {

    protected $fillable = [
        'first_name', 'last_name', 'company', 'email', 'phone',
    ];

    public function getFullNameAttribute() {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function companyIdCompany() {
        return $this->belongsTo('App\Company', 'company');
    }

}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Employee;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use DataTables;

class EmployeeController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        if (Request()->ajax()) {
            $modelDatatables = $this->ajax(Request(), 'index');
            return $modelDatatables->make(true);
        }
        return view('employee.index');
    }

    public function ajax($request, $method) {
        if ($method == 'index') {
            $modelDatatables = Datatables::of(Employee::query())
                    ->addIndexColumn()
                    ->editColumn('company',function($query){
                        return $query->companyIdCompany->name ?? null;
                    })
                    ->addColumn('full_name',function($query){
                        return $query->full_name;
                    })
                    ->addColumn('action', function ($query) {
                        $btnView = "<a type='button' class='btn btn-xs btn-success' href='" . route('employees.show', ['employee' => $query->id]) . "'>View</a>";
                        $btnEdit = "<a type='button' class='btn btn-xs btn-primary' href='" . route('employees.edit', ['employee' => $query->id]) . "'>Edit</a>";
                        $btnDelete = "<a type='button' class='btn btn-xs btn-danger' href='#' data-modal data-route='" . route('employees.destroy', $query->id) . "' data-toggle='modal' data-target='#modal-delete'>Delete</a>";
                        return $btnView . ' ' . $btnEdit . ' ' . $btnDelete;
                    })
                    ->only(['full_name','company','email','phone','action'])->rawColumns(['logo', 'action']);
        }
        return $modelDatatables;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        return view('employee.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        $validator = Validator::make($request->all(), [
            'first_name' => 'required',
            'last_name' => 'required',
            'email' => 'nullable|email',
        ]);
        if($validator->fails()){
            return back()->withErrors($validator)->withInput();
        }
        $input = $request->all();
        $employee = new Employee();
        $employee->fill($input);
        $employee->save();
        \Session::flash('success', 'Successfully Created');
        return redirect(route('employees.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee) {
        return view('employee.show', compact('employee'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee) {
        return view('employee.edit', compact('employee'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee) {
        $validator = Validator::make($request->all(), [
            'first_name' => 'required',
            'last_name' => 'required',
            'email' => 'nullable|email',
        ]);
        if($validator->fails()){
            return back()->withErrors($validator)->withInput();
        }
        $input = $request->all();
        $employee->fill($input);
        $employee->save();
        \Session::flash('success', 'Successfully Updated');
        return redirect(route('employees.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee) {
        $employee->delete();
        \Session::flash('success', 'Successfully Deleted');
        return redirect(back()->getTargetUrl());
    }

}

resources/views/employee/create.blade.php
@extends('layouts.app')

@section('content-header')
    <h1>
        Employee
        <small>Laravel</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{url('/')}}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Employee</li>
    </ol>
@endsection

@section('main-content')
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Employee</h3>
        </div>
        <form method="POST" action="{{ route('employees.store') }}" enctype="multipart/form-data">
            @csrf
            <div class="box-body">
                @include('layouts.components.session_message')
                @component('layouts.components.edit_one_column',['for' => 'first_name','required' => '1','label'=>'First Name']) @slot('field')
                    <input type="text" name="first_name" value="{{old('first_name')}}" required maxlength="254" placeholder="First Name">
                @endslot @endcomponent
                @component('layouts.components.edit_one_column',['for' => 'last_name','required' => '1','label'=>'Last Name']) @slot('field')
                    <input type="text" name="last_name" value="{{old('last_name')}}" required maxlength="254" placeholder="Last Name">
                @endslot @endcomponent
                @component('layouts.components.edit_one_column',['for' => 'company','required' => '0','label'=>'Company']) @slot('field')
                    <select name="company"><option value="">Select Company</option>
                        @foreach (\App\Company::pluck('name', 'id') as $key => $value)
                          <option value="{{ $key }}"> 
                              {{ $value }} 
                          </option>
                        @endforeach
                    </select>
                @endslot @endcomponent
                @component('layouts.components.edit_one_column',['for' => 'email','required' => '0','label'=>'Email']) @slot('field')
                    <input type="email" value="{{old('email')}}" name="email" placeholder="Email">
                @endslot @endcomponent
                @component('layouts.components.edit_one_column',['for' => 'phone','required' => '0','label'=>'Phone']) @slot('field')
                    <input type="tel" value="{{old('phone')}}" name="phone" maxlength="254" placeholder="Phone" pattern="^(\+?6?0)[0|1|2|3|4|6|7|8|9][0-9]{7,9}$">
                    <p class="help-block">Format: +601122224444</p>
                @endslot @endcomponent
            </div>
            <div class='box-footer'>
                <div class='pull-right'>
                    <button type="submit" class="btn btn-success"><i class="fa fa-floppy-o">&nbsp;Save</i></button>
                </div>
                <button type="button" class="btn btn-danger pull-left" onClick="location.href ='{{route('employees.index')}}';"><i class="fa fa-undo"></i> Back</button>
            </div>
        </form>
    </div>
@endsection

resources/views/employee/edit.blade.php
@extends('layouts.app')

@section('content-header')
    <h1>
        Employee
        <small>Laravel</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{url('/')}}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Employee</li>
    </ol>
@endsection

@section('main-content')
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Employee</h3>
        </div>
        <form method="POST" action="{{ route('employees.update',['employee'=>$employee->id]) }}">
            @csrf
            @method('PUT')
            <div class="box-body">
                @include('layouts.components.session_message')
                @component('layouts.components.edit_one_column',['for' => 'first_name','required' => '1','label'=>'First Name']) @slot('field')
                    <input type="text" name="first_name" required value="{{old('first_name') ?? $employee->first_name}}" maxlength="254" placeholder="First Name">
                @endslot @endcomponent
                @component('layouts.components.edit_one_column',['for' => 'last_name','required' => '1','label'=>'Last Name']) @slot('field')
                    <input type="text" name="last_name" required value="{{old('last_name') ?? $employee->last_name}}" maxlength="254" placeholder="Last Name">
                @endslot @endcomponent
                @component('layouts.components.edit_one_column',['for' => 'company','required' => '0','label'=>'Company']) @slot('field')
                    <select name="company"><option value="">Select Company</option>
                        @foreach (\App\Company::pluck('name', 'id') as $key => $value)
                          <option value="{{ $key }}" {{ ($key == (old('company') ?? $employee->company)) ? 'selected' : '' }}> 
                              {{ $value }} 
                          </option>
                        @endforeach
                    </select>
                @endslot @endcomponent
                @component('layouts.components.edit_one_column',['for' => 'email','required' => '0','label'=>'Email']) @slot('field')
                    <input type="email" name="email" value="{{old('email') ?? $employee->email}}" placeholder="Email">
                @endslot @endcomponent
                @component('layouts.components.edit_one_column',['for' => 'phone','required' => '0','label'=>'Phone']) @slot('field')
                    <input type="tel" name="phone" value="{{old('phone') ?? $employee->phone}}" maxlength="254" placeholder="Phone" pattern="^(\+?6?0)[0|1|2|3|4|6|7|8|9][0-9]{7,9}$">
                    <p class="help-block">Format: +601122224444</p>
                @endslot @endcomponent
            </div>
            <div class='box-footer'>
                <div class='pull-right'>
                    <button type="submit" class="btn btn-success"><i class="fa fa-floppy-o">&nbsp;Save</i></button>
                </div>
                <button type="button" class="btn btn-danger pull-left" onClick="location.href ='{{route('employees.index')}}';"><i class="fa fa-undo"></i> Back</button>
            </div>
        </form>
    </div>
@endsection

resources/views/employee/index.blade.php
@extends('layouts.app')

@section('content-header')
    <h1>
        Employees
        <small>Laravel</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{url('/')}}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Employees</li>
    </ol>
@endsection

@section('main-content')
    @push('modals')
        @include('layouts.components.modal_delete')
    @endpush 
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Employees</h3>
        </div>
        <div class="box-body">
            @include('layouts.components.session_message')
            <div class="table-responsive no-padding" style="border: none;">
                @component('layouts.components.table_ajax', ['tname' => 'employees_table_ajax']) @slot('url')
                    {{ route('employees.index')}}
                @endslot @slot('thead')
                    <th style='width: 30px;'>No.</th>
                    <th>Full Name</th>
                    <th>Company</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th style="width:66px;">Action</th>
                @endslot @slot('tbody')
                    { data: 'DT_RowIndex', orderable: false, searchable: false },
                    { data: 'full_name', name: 'full_name' },
                    { data: 'company', name: 'company' },
                    { data: 'email', name: 'email' },
                    { data: 'phone', name: 'phone' },
                    { data: 'action', name: 'action' },
                @endslot @slot('firstScript')
                    dom: '<"row "<"col-sm-4"<B> ><"col-sm-4" f ><"col-sm-4" l>>rtip',
                    columnDefs: [{ orderable: false, targets: [5] }],
                    buttons: [
                        {
                            className: 'btn-sm btn-info',
                            text: '<i class="fa fa-plus"></i> Create Employee',
                            action: function ( e, dt, node, config ) {
                                window.location = '{{ route('employees.create') }}';
                            }
                        },
                    ],
                @endslot @slot('secondScript')
                @endslot @endcomponent  
            </div>
        </div>
    </div>
@endsection  

resources/views/employee/show.blade.php
@extends('layouts.app')

@section('content-header')
    <h1>
        Employee
        <small>Laravel</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{url('/')}}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Employee</li>
    </ol>
@endsection

@section('main-content')
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Employee</h3>
        </div>
        <div class="box-body">
            @include('layouts.components.session_message')
            @component('layouts.components.show_one_column',['label'=>'Full Name']) @slot('field')
                {{$employee->full_name}}
            @endslot @endcomponent
            @component('layouts.components.show_one_column',['label'=>'Company']) @slot('field')
                {{$employee->companyIdCompany->name ?? null}}
            @endslot @endcomponent
            @component('layouts.components.show_one_column',['label'=>'Email']) @slot('field')
                <a href='mailto:{{$employee->email}}'>{{$employee->email}}</a>
            @endslot @endcomponent
            @component('layouts.components.show_one_column',['label'=>'Phone']) @slot('field')
                {{$employee->phone}}
            @endslot @endcomponent
        </div>
        <div class='box-footer'>
            <div class='pull-right'>
                <button type="button" onClick="location.href ='{{route('employees.edit',['employee'=>$employee->id])}}';" class="btn btn-primary"><i class="fa fa-pencil">&nbsp;Edit</i></button>
            </div>
            <button type="button" class="btn btn-danger pull-left" onClick="location.href ='{{route('employees.index')}}';"><i class="fa fa-undo"></i> Back</button>
        </div>
    </div>
@endsection