routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth']], function () {
    Route::resource('companies', 'CompanyController');
    Route::resource('employees', 'EmployeeController');
});

Auth::routes(['register' => false]);
Route::get('/home', 'HomeController@index')->name('home');

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model {

    protected $fillable = [
        'name', 'email', 'logo', 'website',
    ];

}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use DataTables;
use Illuminate\Support\Facades\Storage;

class CompanyController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        if (Request()->ajax()) {
            $modelDatatables = $this->ajax(Request(), 'index');
            return $modelDatatables->make(true);
        }
        return view('company.index');
    }
    
    public function ajax($request, $method) {
        if ($method == 'index') {
            $modelDatatables = Datatables::of(Company::query())
                    ->addIndexColumn()
                    ->editColumn('logo',function($query){
                        if(isset($query->logo)){
                            return '<img style="width: 65px;height: 100%;" src="'.url('storage/'.$query->logo).'">';
                        }
                    })
                    ->addColumn('action', function ($query) {
                        $btnView = "<a type='button' class='btn btn-xs btn-success' href='".route('companies.show',['company'=>$query->id])."'>View</a>";
                        $btnEdit = "<a type='button' class='btn btn-xs btn-primary' href='".route('companies.edit',['company'=>$query->id])."'>Edit</a>";
                        $btnDelete = "<a type='button' class='btn btn-xs btn-danger' href='#' data-modal data-route='" . route('companies.destroy', $query->id) . "' data-toggle='modal' data-target='#modal-delete'>Delete</a>";
                        return $btnView.' '.$btnEdit.' '.$btnDelete;
                    })->rawColumns(['logo', 'action']);
        }
        return $modelDatatables;
    }  

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        return view('company.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'email' => 'nullable|email',
            'logo' => 'nullable|mimes:jpeg,jpg,png|max:10000',
        ]);
        if($validator->fails()){
            return back()->withErrors($validator)->withInput();
        }
        $input = $request->all();
        $company = new Company();
        $company->fill($input);
        if(isset($request->logo)){
            $filenameWithExt = time().'_'.$request->logo->getClientOriginalName();
            $request->logo->storeAs('public', $filenameWithExt);
            $company->logo = $filenameWithExt;
        }
        $company->save();
        \Session::flash('success', 'Successfully Created');
        return redirect(route('companies.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company) {
        return view('company.show', compact('company'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company) {
        return view('company.edit', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Company $company) {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'email' => 'nullable|email',
            'logo' => 'nullable|mimes:jpeg,jpg,png|max:10000',
        ]);
        if($validator->fails()){
            return back()->withErrors($validator)->withInput();
        }
        $input = $request->all();
        if(isset($request->logo) && isset($company->logo)){
            Storage::delete('public/' . $company->logo);
        }
        $company->fill($input);
        if(isset($request->logo)){
            $filenameWithExt = time().'_'.$request->logo->getClientOriginalName();
            $request->logo->storeAs('public', $filenameWithExt);
            $company->logo = $filenameWithExt;
        }
        $company->save();
        \Session::flash('success', 'Successfully Updated');
        return redirect(back()->getTargetUrl());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company) {
        if(isset($company->logo)){
            Storage::delete('public/' . $company->logo);
        }
        $company->delete();
        \Session::flash('success', 'Successfully Deleted');
        return redirect(back()->getTargetUrl());
    }

}

resources/views/company/create.blade.php
@extends('layouts.app')

@section('content-header')
    <h1>
        Company
        <small>Laravel</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{url('/')}}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Company</li>
    </ol>
@endsection

@section('main-content')
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Company</h3>
        </div>
        <form method="POST" action="{{ route('companies.store') }}" enctype="multipart/form-data">
            @csrf
            <div class="box-body">
                @include('layouts.components.session_message')
                @component('layouts.components.edit_one_column',['for' => 'name','required' => '1','label'=>'Name']) @slot('field')
                    <input type="text" name="name" value="{{old('name')}}" required maxlength="254" placeholder="Name">
                @endslot @endcomponent
                @component('layouts.components.edit_one_column',['for' => 'email','required' => '0','label'=>'Email']) @slot('field')
                    <input type="email" name="email" value="{{old('email')}}" placeholder="Email">
                @endslot @endcomponent
                @component('layouts.components.edit_one_column',['for' => 'logo','required' => '0','label'=>'Logo']) @slot('field')
                    <input type="file" name="logo" accept="image/jpeg, image/png">
                    <p class="help-block">File format allowed: jpeg, jpg, png</p>
                @endslot @endcomponent
                @component('layouts.components.edit_one_column',['for' => 'website','required' => '0','label'=>'Website']) @slot('field')
                    <input type="text" name="website" value="{{old('website')}}" maxlength="254" placeholder="Website">
                @endslot @endcomponent
            </div>
            <div class='box-footer'>
                <div class='pull-right'>
                    <button type="submit" class="btn btn-success"><i class="fa fa-floppy-o">&nbsp;Save</i></button>
                </div>
                <button type="button" class="btn btn-danger pull-left" onClick="location.href ='{{route('companies.index')}}';"><i class="fa fa-undo"></i> Back</button>
            </div>
        </form>
    </div>
@endsection

resources/views/company/edit.blade.php
@extends('layouts.app')

@section('content-header')
    <h1>
        Company
        <small>Laravel</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{url('/')}}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Company</li>
    </ol>
@endsection

@section('main-content')
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Company</h3>
        </div>
        <form method="POST" action="{{ route('companies.update',['company'=>$company->id]) }}" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="box-body">
                @include('layouts.components.session_message')
                @component('layouts.components.edit_one_column',['for' => 'name','required' => '1','label'=>'Name']) @slot('field')
                    <input type="text" name="name" value="{{old('name') ?? $company->name}}" required maxlength="254" placeholder="Name">
                @endslot @endcomponent
                @component('layouts.components.edit_one_column',['for' => 'email','required' => '0','label'=>'Email']) @slot('field')
                    <input type="email" name="email" value="{{old('email') ?? $company->email}}" placeholder="Email">
                @endslot @endcomponent
                @component('layouts.components.edit_one_column',['for' => 'logo','required' => '0','label'=>'Logo']) @slot('field')
                    @if(isset($company->logo))
                        <img style="width: 65px;height: 100%;" src="{{url('storage/'.$company->logo)}}">
                    @else
                        Please Upload
                    @endif
                    <input type="file" name="logo" accept="image/jpeg, image/png">
                    <p class="help-block">File format allowed: jpeg, jpg, png</p>
                @endslot @endcomponent
                @component('layouts.components.edit_one_column',['for' => 'website','required' => '0','label'=>'Website']) @slot('field')
                    <input type="text" name="website" value="{{old('website') ?? $company->website}}" maxlength="254" placeholder="Website">
                @endslot @endcomponent
            </div>
            <div class='box-footer'>
                <div class='pull-right'>
                    <button type="submit" class="btn btn-success"><i class="fa fa-floppy-o">&nbsp;Save</i></button>
                </div>
                <button type="button" class="btn btn-danger pull-left" onClick="location.href ='{{route('companies.index')}}';"><i class="fa fa-undo"></i> Back</button>
            </div>
        </form>
    </div>
@endsection

resources/views/company/index.blade.php
@extends('layouts.app')

@section('content-header')
    <h1>
        Companies
        <small>Laravel</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{url('/')}}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Companies</li>
    </ol>
@endsection

@section('main-content')
    @push('modals')
        @include('layouts.components.modal_delete')
    @endpush 
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Companies</h3>
        </div>
        <div class="box-body">
            @include('layouts.components.session_message')
            <div class="table-responsive no-padding" style="border: none;">
                @component('layouts.components.table_ajax', ['tname' => 'companies_table_ajax']) @slot('url')
                    {{ route('companies.index')}}
                @endslot @slot('thead')
                    <th style='width: 30px;'>No.</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Logo</th>
                    <th>Website</th>
                    <th style="width:66px;">Action</th>
                @endslot @slot('tbody')
                    { data: 'DT_RowIndex', orderable: false, searchable: false },
                    { data: 'name', name: 'name' },
                    { data: 'email', name: 'email' },
                    { data: 'logo', name: 'logo' },
                    { data: 'website', name: 'website' },
                    { data: 'action', name: 'action' },
                @endslot @slot('firstScript')
                    dom: '<"row "<"col-sm-4"<B> ><"col-sm-4" f ><"col-sm-4" l>>rtip',
                    columnDefs: [{ orderable: false, targets: [5] }],
                    buttons: [
                        {
                            className: 'btn-sm btn-info',
                            text: '<i class="fa fa-plus"></i> Create Company',
                            action: function ( e, dt, node, config ) {
                                window.location = '{{ route('companies.create') }}';
                            }
                        },
                    ],
                @endslot @slot('secondScript')
                @endslot @endcomponent  
            </div>
        </div>
    </div>
@endsection  

resources/views/company/show.blade.php
@extends('layouts.app')

@section('content-header')
    <h1>
        Company
        <small>Laravel</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{url('/')}}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Company</li>
    </ol>
@endsection

@section('main-content')
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Company</h3>
        </div>
        <div class="box-body">
            @include('layouts.components.session_message')
            @component('layouts.components.show_one_column',['label'=>'Name']) @slot('field')
                {{$company->name}}
            @endslot @endcomponent
            @component('layouts.components.show_one_column',['label'=>'Email']) @slot('field')
                {{$company->email}}
            @endslot @endcomponent
            @component('layouts.components.show_one_column',['label'=>'Logo']) @slot('field')
                @if(isset($company->logo))
                    <img style="width: 65px;height: 100%;" src="{{url('storage/'.$company->logo)}}">
                @else
                    Please Upload
                @endif
            @endslot @endcomponent
            @component('layouts.components.show_one_column',['label'=>'Website']) @slot('field')
                {{$company->website}}
            @endslot @endcomponent
        </div>
        <div class='box-footer'>
            <div class='pull-right'>
                <button type="button" onClick="location.href ='{{route('companies.edit',['company'=>$company->id])}}';" class="btn btn-primary"><i class="fa fa-pencil">&nbsp;Edit</i></button>
            </div>
            <button type="button" class="btn btn-danger pull-left" onClick="location.href ='{{route('companies.index')}}';"><i class="fa fa-undo"></i> Back</button>
        </div>
    </div>
@endsection